name: Generate Metrics

on:
  schedule:
    - cron: "0 */12 * * *"  
  workflow_dispatch:         

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8
